language: Objective-C

cache:
- bundler
- cocoapods

podfile: ./PPEventRegistryAPI

osx_image: xcode8

before_install:
- bundle
- pod repo update --silent
- pod install --project-directory=PPEventRegistryAPI
- pod install --project-directory=Example

notifications:
  email: false

env:
  global:
  - WORKSPACE=PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace
  - WORKSPACE_EXAMPLE=Example/PPEventRegistryTest.xcworkspace
  - EXAMPLE_IOS="PPEventRegistryTest"
  - EXAMPLE_TVOS="PPEventRegistryTest tvOS"
  - EXAMPLE_WATCHOS="PPEventRegistryTest watchOS"
  - EXAMPLE_MACOS="PPEventRegistryTest macOS"
  - SCHEME_IOS="PPEventRegistryAPI iOS"
  - SCHEME_TVOS="PPEventRegistryAPI tvOS"
  - SCHEME_WATCHOS="PPEventRegistryAPI watchOS"
  - SCHEME_MACOS="PPEventRegistryAPI macOS"
  - SDK_IOS=iphonesimulator10.0
  - SDK_WATCHOS=watchsimulator3.0
  - SDK_TVOS=appletvsimulator10.0
  - SDK_MACOS=macosx10.12
  - DEST_IOS10="name=iPhone 7,OS=10.0"
  - DEST_IOS9="name=iPhone 5,OS=9.3"
  - DEST_IOS8="name=iPhone 5,OS=8.4"
  - DEST_WATCHOS3="name=Apple Watch - 42mm,OS=3.0"
  - DEST_WATCHOS2="name=Apple Watch - 42mm,OS=2.2"
  - DEST_TVOS10="name=Apple TV 1080p,OS=10.0"
  - DEST_TVOS9="name=Apple TV 1080p,OS=9.2"
  - DEST_MACOS="arch=x86_64"
  matrix:
  - DESTINATION="$DEST_IOS10"    SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="YES" SEND_COVERAGE="YES" POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_IOS"     DEST_EXAMPLE="$DEST_IOS10"
  - DESTINATION="$DEST_IOS9"     SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_IOS"     DEST_EXAMPLE="$DEST_IOS9"
  - DESTINATION="$DEST_IOS8"     SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_IOS"     DEST_EXAMPLE="$DEST_IOS8"
  - DESTINATION="$DEST_WATCHOS3" SDK="$SDK_WATCHOS" SCHEME="$SCHEME_WATCHOS" RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="YES" CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_WATCHOS" DEST_EXAMPLE="$DEST_IOS10"
  - DESTINATION="$DEST_WATCHOS2" SDK="$SDK_WATCHOS" SCHEME="$SCHEME_WATCHOS" RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="YES" SCHEME_EXAMPLE="$EXAMPLE_WATCHOS" DEST_EXAMPLE="$DEST_IOS10"
  - DESTINATION="$DEST_TVOS10"   SDK="$SDK_TVOS"    SCHEME="$SCHEME_TVOS"    RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_TVOS"    DEST_EXAMPLE="$DEST_TVOS10"
  - DESTINATION="$DEST_TVOS9"    SDK="$SDK_TVOS"    SCHEME="$SCHEME_TVOS"    RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_TVOS"    DEST_EXAMPLE="$DEST_TVOS9"
  - DESTINATION="$DEST_MACOS"    SDK="$SDK_MACOS"   SCHEME="$SCHEME_MACOS"   RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"  SCHEME_EXAMPLE="$EXAMPLE_MACOS"   DEST_EXAMPLE="$DEST_MACOS"

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild build-for-testing test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  else
    xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  fi

- xcodebuild build -workspace "$WORKSPACE_EXAMPLE" -scheme "$SCHEME_EXAMPLE" -destination "$DEST_EXAMPLE" ONLY_ACTIVE_ARCH=YES | xcpretty -c;

- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi

- if [ $CARTHAGE == "YES" ]; then
    carthage build --no-skip-current;
  fi

after_success:
  - test $SEND_COVERAGE = "YES" && ./.coverage.sh

before_deploy:
  - carthage build --no-skip-current
  - carthage archive PPEventRegistryAPI

deploy:
  provider: releases
  api_key:
    secure: y2mzME6iUEon78DwJnp6IXYIixF7voRD1todBK39DVIYYMoA2LwwA0R/L4xKC5JITapqRA/RorAuNHjb99Ps4NvtpFrZ35UeXspRKa2ekoRoX0w6YQ7ieumSBlRErq0aJ7uCYphfLUE6VeAO+hB9moSRs0YoxVIKFkHOjtvqqDJ5YZvezau29uhkR23rnVyay2AXtVgDiQMetwveenh98hC8q4ytMT5o4ndZ6ruTMgc+elfl8EJj0VQTvjGagLWaiEidvyLzWbvSNM2Hh/hMMTDUQCXMdrtipuV+Qu53avHMoxLksRNz/c35DjVBLqVXgEaoytAT9lrsD1CwtHtv0TsXRuIGpXI5mMv3JpZtWSrFPVtytjK8kn/n7crisluTjuL9ILrE4zSndoEm3K5XL4lrqLWQ/fgwT0ag8SRw88/dzQsselpTzceb8bbFaat/qS3dMoWmDRmLU83YyI2oDrXkAObWz9//ffHMJj3RZ6jocwQ6Pd4HgDSBHfrVUG8MBQ1S+d5GAaEAsO0mKVQQRYkQGVZMfVdQa8BfSuMtHlcsB0Qt50n/INVkk+oYgJd3r+eOvuYxtk/G9LHdB2kaEZlTCsE1XX8GsAqPaVTYb4f8/CODGfyBa6JKmShEj0U2gNX+s4zuNs4E+R3aGhx3kXC1B3Yv97h4mWTh0qiZ4qw=
  file: PPEventRegistryAPI.framework.zip
  skip_cleanup: true
  on:
    repo: pantuspavel/PPEventRegistryAPI
    tags: true
