language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod repo update --silent
- pod install --project-directory=PPEventRegistryAPI

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - WORKSPACE=PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace
  - SCHEME_IOS="PPEventRegistryAPI iOS"
  - SCHEME_TVOS="PPEventRegistryAPI tvOS"
  - SCHEME_WATCHOS="PPEventRegistryAPI watchOS"
  - SCHEME_MACOS="PPEventRegistryAPI macOS"
  - SDK_IOS=iphonesimulator10.0
  - SDK_WATCHOS=watchsimulator3.0
  - SDK_TVOS=appletvsimulator10.0
  - SDK_MACOS=macosx10.12
  - DEST_IOS10="name=iPhone 6s,OS=10.0"
  - DEST_IOS9="name=iPhone 5,OS=9.3"
  - DEST_IOS8="name=iPhone 5,OS=8.4"
  - DEST_WATCHOS3="name=Apple Watch - 42mm,OS=3.0"
  - DEST_WATCHOS2="name=Apple Watch - 42mm,OS=2.2"
  - DEST_TVOS10="name=Apple TV 1080p,OS=10.0"
  - DEST_TVOS9="name=Apple TV 1080p,OS=9.2"
  - DEST_MACOS="arch=x86_64"
  matrix:
    - DESTINATION="$DEST_IOS10"    SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="YES" SEND_COVERAGE="YES" POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="$DEST_IOS9"     SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="$DEST_IOS8"     SDK="$SDK_IOS"     SCHEME="$SCHEME_IOS"     RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="$DEST_WATCHOS3" SDK="$SDK_WATCHOS" SCHEME="$SCHEME_WATCHOS" RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="YES" CARTHAGE="NO"
    - DESTINATION="$DEST_WATCHOS2" SDK="$SDK_WATCHOS" SCHEME="$SCHEME_WATCHOS" RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="YES"
    - DESTINATION="$DEST_TVOS10"   SDK="$SDK_TVOS"    SCHEME="$SCHEME_TVOS"    RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="$DEST_TVOS9"    SDK="$SDK_TVOS"    SCHEME="$SCHEME_TVOS"    RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="$DEST_MACOS"    SDK="$SDK_MACOS"   SCHEME="$SCHEME_MACOS"   RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild build-for-testing test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  else
    xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  fi

- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi

- if [ $CARTHAGE == "YES" ]; then
    carthage build --no-skip-current;
  fi

after_success:
- test $SEND_COVERAGE = "YES" && ./.coverage.sh
